---
abstract: 'An evolution of POD'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  FindBin: '0'
  Path::Iterator::Rule: '0'
  Path::Tiny: '0'
  Test::Fatal: '0'
  Test::More: '0'
  Test::Requires: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MetaPOD
provides:
  MetaPOD:
    file: lib/MetaPOD.pm
    version: v0.4.0
  MetaPOD::Assembler:
    file: lib/MetaPOD/Assembler.pm
    version: v0.4.0
  MetaPOD::Exception:
    file: lib/MetaPOD/Exception.pm
    version: v0.4.0
  MetaPOD::Exception::Decode::Data:
    file: lib/MetaPOD/Exception/Decode/Data.pm
    version: v0.4.0
  MetaPOD::Extractor:
    file: lib/MetaPOD/Extractor.pm
    version: v0.4.0
  MetaPOD::Result:
    file: lib/MetaPOD/Result.pm
    version: v0.4.0
  MetaPOD::Role::Format:
    file: lib/MetaPOD/Role/Format.pm
    version: v0.4.0
recommends:
  Moo: '1.000008'
requires:
  Carp: '0'
  Data::Dump: '0'
  List::AllUtils: '0'
  Module::Runtime: '0'
  Moo: '1.000008'
  Moo::Role: '0'
  Pod::Eventual: '0'
  Throwable::Error: '0'
  perl: '5.006'
  strict: '0'
  version: '0.77'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/MetaPOD/issues
  homepage: https://github.com/kentnl/MetaPOD
  repository: https://github.com/kentnl/MetaPOD.git
version: v0.4.0
